### ISSUE TITLE
all errors with rust panics need review for message bubbling

### ISSUE THREAD

**Issue by dpastoor** [A2-ai/dvs#9]
eg run dvs_init from somewhere other than the repo:

![image](https://github.com/A2-ai/dvs/assets/3196313/2937cf8b-1b19-483a-8a4f-74e5c6fe1a8b)

**Comment by dpastoor** [comment]
to demonstrate a snippet of code and the behavior making sure its run in a non-git dir:

```
> withr::with_dir("/tmp", dvs_init("/tmp/test"))
thread '<unnamed>' panicked at /cluster-data/user-homes/devin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:64:13:
called `Result::unwrap()` on an `Err` value: Other("git repository not found: make sure you're in an active git repository. could not find git repo root; make sure you're in an active git repository: .")
Error in dvs_init_impl(storage_directory, permissions, group) : 
  user function panicked: dvs_init_impl
thread '<unnamed>' panicked at src/lib.rs:48:1:
explicit panic
> packageVersion("dvs")
[1] ‘0.0.1’
```

**Comment by dpastoor** [comment]
![image](https://github.com/A2-ai/dvs/assets/3196313/dd8b5f07-6f79-4dd3-bdb2-6681e216d43d)

coming along...
